"""update the enums

Revision ID: 031b453466a7
Revises: 7f1a80898870
Create Date: 2025-08-24 15:51:56.596876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '031b453466a7'
down_revision: Union[str, Sequence[str], None] = '7f1a80898870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predictions', 'payment_status',
               existing_type=mysql.ENUM('pending', 'completed', 'failed'),
               type_=sa.Enum('Pending', 'Complete', 'Failed', name='payment_status'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predictions', 'payment_status',
               existing_type=sa.Enum('Pending', 'Complete', 'Failed', name='payment_status'),
               type_=mysql.ENUM('pending', 'completed', 'failed'),
               existing_nullable=True)
    # ### end Alembic commands ###
