"""Enum Issue

Revision ID: 087984c0dde9
Revises: 656c1ec28961
Create Date: 2025-08-24 16:13:37.701817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087984c0dde9'
down_revision: Union[str, Sequence[str], None] = '656c1ec28961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('payment_status', sa.Enum('Pending', 'Complete', 'Failed', name='payment_status'), nullable=True))
    op.add_column('transactions', sa.Column('tx_type', sa.Enum('Stake', 'Reward', 'Deposit', 'Withdrawal', name='transaction_type'), nullable=True))
    op.add_column('transactions', sa.Column('status', sa.Enum('Pending', 'Completed', 'Failed', name='transaction_status'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'tx_type')
    op.drop_column('predictions', 'payment_status')
    # ### end Alembic commands ###
