"""TOken confirmation

Revision ID: 19cfb3c6a813
Revises: 5d416e6d4809
Create Date: 2025-09-04 23:22:28.538487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '19cfb3c6a813'
down_revision: Union[str, Sequence[str], None] = '5d416e6d4809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'tx_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('tx_type', mysql.ENUM('Stake', 'Reward', 'Deposit', 'Withdrawal'), nullable=True))
    # ### end Alembic commands ###
