"""TOken confirmation

Revision ID: 251235e85541
Revises: 19cfb3c6a813
Create Date: 2025-09-04 23:22:54.799782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251235e85541'
down_revision: Union[str, Sequence[str], None] = '19cfb3c6a813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('tx_type', sa.Enum('Stake', 'Reward', 'Deposit', 'Withdrawal', 'Proposal', name='transaction_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'tx_type')
    # ### end Alembic commands ###
