"""txt type

Revision ID: 48aa56fa4093
Revises: e923c6b1d893
Create Date: 2025-09-15 15:50:51.983924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '48aa56fa4093'
down_revision: Union[str, Sequence[str], None] = 'e923c6b1d893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'tx_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('tx_type', mysql.ENUM('Stake', 'Reward', 'Deposit', 'Withdrawal', 'Proposal'), nullable=True))
    # ### end Alembic commands ###
