"""Enum Issue

Revision ID: 5679acfcc0f9
Revises: aabbcefa875e
Create Date: 2025-08-24 16:09:25.804173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5679acfcc0f9'
down_revision: Union[str, Sequence[str], None] = 'aabbcefa875e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('result', sa.Enum('Pending', 'Correct', 'Incorrect', name='prediction_result'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'result')
    # ### end Alembic commands ###
