"""TOken confirmation

Revision ID: 5d416e6d4809
Revises: 954606da598f
Create Date: 2025-09-04 23:12:56.301788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d416e6d4809'
down_revision: Union[str, Sequence[str], None] = '954606da598f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_proposals', sa.Column('payment_status', sa.Enum('Pending', 'Complete', 'Failed', name='payment_status'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_proposals', 'payment_status')
    # ### end Alembic commands ###
