"""Add reward column

Revision ID: 610112d0b723
Revises: 828f4aa39792
Create Date: 2025-09-02 16:06:29.192351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610112d0b723'
down_revision: Union[str, Sequence[str], None] = '828f4aa39792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('reward', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'reward')
    # ### end Alembic commands ###
