"""Enum Issue

Revision ID: 656c1ec28961
Revises: 5679acfcc0f9
Create Date: 2025-08-24 16:12:23.365350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '656c1ec28961'
down_revision: Union[str, Sequence[str], None] = '5679acfcc0f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'payment_status')
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'tx_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('tx_type', mysql.ENUM('stake', 'reward', 'deposit', 'withdrawal'), nullable=True))
    op.add_column('transactions', sa.Column('status', mysql.ENUM('pending', 'completed', 'failed'), nullable=True))
    op.add_column('predictions', sa.Column('payment_status', mysql.ENUM('Pending', 'Complete', 'Failed'), nullable=True))
    # ### end Alembic commands ###
