"""transaction columns

Revision ID: 7f1a80898870
Revises: f2ded379b4be
Create Date: 2025-08-19 00:32:13.484593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1a80898870'
down_revision: Union[str, Sequence[str], None] = 'f2ded379b4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpesa_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_no', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('checkout_request_id', sa.String(length=200), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'complete', name='transactionstatusenum'), nullable=True),
    sa.Column('receipt_no', sa.String(length=200), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=200), nullable=True),
    sa.Column('billref', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_no')
    )
    op.add_column('predictions', sa.Column('payment_reference', sa.String(length=100), nullable=True))
    op.add_column('predictions', sa.Column('payment_status', sa.Enum('pending', 'completed', 'failed', name='payment_status'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'payment_status')
    op.drop_column('predictions', 'payment_reference')
    op.drop_table('mpesa_transactions')
    # ### end Alembic commands ###
