"""Enum Issue

Revision ID: 828f4aa39792
Revises: 087984c0dde9
Create Date: 2025-08-24 16:20:57.329794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '828f4aa39792'
down_revision: Union[str, Sequence[str], None] = '087984c0dde9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'status',
               existing_type=mysql.ENUM('Pending', 'Completed', 'Failed'),
               type_=sa.Enum('Pending', 'Complete', 'Failed', name='transaction_status'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'status',
               existing_type=sa.Enum('Pending', 'Complete', 'Failed', name='transaction_status'),
               type_=mysql.ENUM('Pending', 'Completed', 'Failed'),
               existing_nullable=True)
    # ### end Alembic commands ###
