"""proposal reference

Revision ID: 954606da598f
Revises: 610112d0b723
Create Date: 2025-09-04 22:04:32.710843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954606da598f'
down_revision: Union[str, Sequence[str], None] = '610112d0b723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal_votes', sa.Column('payment_reference', sa.String(length=100), nullable=True))
    op.add_column('token_proposals', sa.Column('payment_reference', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_proposals', 'payment_reference')
    op.drop_column('proposal_votes', 'payment_reference')
    # ### end Alembic commands ###
