"""example_update2

Revision ID: a598ff513fe4
Revises: bb7e60eda00f
Create Date: 2025-08-07 16:25:42.612183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a598ff513fe4'
down_revision: Union[str, Sequence[str], None] = 'bb7e60eda00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_urll', sa.String(length=255), nullable=True))
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('users', 'avatar_urll')
    # ### end Alembic commands ###
