"""Enum Issue

Revision ID: aabbcefa875e
Revises: d2f03b9e5a07
Create Date: 2025-08-24 16:08:59.794038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aabbcefa875e'
down_revision: Union[str, Sequence[str], None] = 'd2f03b9e5a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'result')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('result', mysql.ENUM('pending', 'correct', 'incorrect'), nullable=True))
    # ### end Alembic commands ###
