"""example_update

Revision ID: c59edd323fb9
Revises: d82379258a05
Create Date: 2025-08-07 16:20:01.428506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c59edd323fb9'
down_revision: Union[str, Sequence[str], None] = 'd82379258a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('market_sentiment',
    # sa.Column('id', sa.String(length=36), nullable=False),
    # sa.Column('token_id', sa.String(length=36), nullable=True),
    # sa.Column('sentiment_score', sa.Float(), nullable=False),
    # sa.Column('bullish_percentage', sa.Integer(), nullable=True),
    # sa.Column('bearish_percentage', sa.Integer(), nullable=True),
    # sa.Column('neutral_percentage', sa.Integer(), nullable=True),
    # sa.Column('data_source', sa.String(length=50), nullable=True),
    # sa.Column('timestamp', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('notifications',
    # sa.Column('id', sa.String(length=36), nullable=False),
    # sa.Column('user_id', sa.String(length=36), nullable=True),
    # sa.Column('title', sa.String(length=255), nullable=False),
    # sa.Column('message', sa.Text(), nullable=False),
    # sa.Column('notification_type', sa.Enum('prediction_result', 'reward', 'price_alert', 'system', name='notificationtype'), nullable=False),
    # sa.Column('is_read', sa.Boolean(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['wallet_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'avatar_url')
    op.drop_table('notifications')
    op.drop_table('market_sentiment')
    # ### end Alembic commands ###
