"""initialization

Revision ID: d82379258a05
Revises: 0bb77da6327b
Create Date: 2025-08-07 16:14:56.517465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd82379258a05'
down_revision: Union[str, Sequence[str], None] = '0bb77da6327b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('symbol', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('logo_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('symbol'), 'tokens', ['symbol'], unique=True)
    op.create_table('predictions',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('token_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('target_timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('predicted_price', mysql.FLOAT(), nullable=False),
    sa.Column('current_price', mysql.FLOAT(), nullable=False),
    sa.Column('confidence', mysql.FLOAT(), nullable=True),
    sa.Column('stake_amount', mysql.FLOAT(), nullable=False),
    sa.Column('result', mysql.ENUM('pending', 'correct', 'incorrect'), nullable=True),
    sa.Column('resolution_timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('resolution_method', mysql.ENUM('exact', 'threshold', 'range', 'percent_delta'), nullable=True),
    sa.Column('payment_method', mysql.ENUM('mpesa', 'usdt', 'internal'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], name=op.f('predictions_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('predictions_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_settings',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('email_notifications', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('push_notifications', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('prediction_reminders', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('public_profile', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('show_prediction_history', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_settings_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('user_achievements',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('achievement_type', mysql.ENUM('first_prediction', 'accuracy_master', 'high_roller', 'streak_master', 'community_leader'), nullable=False),
    sa.Column('earned_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_achievements_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_wallets',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('balance', mysql.FLOAT(), nullable=True),
    sa.Column('total_staked', mysql.FLOAT(), nullable=True),
    sa.Column('total_rewards', mysql.FLOAT(), nullable=True),
    sa.Column('pending_rewards', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_wallets_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('user_id'), 'user_wallets', ['user_id'], unique=True)
    op.create_table('transactions',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('tx_type', mysql.ENUM('stake', 'reward', 'deposit', 'withdrawal'), nullable=True),
    sa.Column('status', mysql.ENUM('pending', 'completed', 'failed'), nullable=True),
    sa.Column('payment_method', mysql.ENUM('mpesa', 'usdt', 'internal'), nullable=True),
    sa.Column('tx_hash', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('mpesa_receipt', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('transactions_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('proposal_votes',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('proposal_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['token_proposals.id'], name=op.f('proposal_votes_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('proposal_votes_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('token_proposals',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('proposed_by', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('token_symbol', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('token_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.ENUM('active', 'approved', 'rejected', 'expired'), nullable=True),
    sa.Column('total_votes', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('votes_needed', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], name=op.f('token_proposals_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('withdrawals',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('withdrawal_method', mysql.ENUM('USDT', 'MPESA'), nullable=False),
    sa.Column('wallet_address', mysql.VARCHAR(length=42), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('status', mysql.ENUM('pending', 'processing', 'completed', 'failed'), nullable=True),
    sa.Column('transaction_hash', mysql.VARCHAR(length=66), nullable=True),
    sa.Column('mpesa_receipt', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('processed_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('withdrawals_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ai_predictions',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('token_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('target_timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('predicted_price', mysql.FLOAT(), nullable=False),
    sa.Column('confidence_score', mysql.FLOAT(), nullable=True),
    sa.Column('extra_data', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], name=op.f('ai_predictions_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('wallet_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('auth_type', mysql.ENUM('email', 'wallet'), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('wallet_address'), 'users', ['wallet_address'], unique=True)
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.create_table('market_sentiment',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('token_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('sentiment_score', mysql.FLOAT(), nullable=False),
    sa.Column('bullish_percentage', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bearish_percentage', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('neutral_percentage', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_source', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], name=op.f('market_sentiment_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notifications',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('notification_type', mysql.ENUM('prediction_result', 'reward', 'price_alert', 'system'), nullable=False),
    sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
