"""Voting process

Revision ID: db70a71f8846
Revises: 251235e85541
Create Date: 2025-09-15 14:45:55.555021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db70a71f8846'
down_revision: Union[str, Sequence[str], None] = '251235e85541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_proposals', sa.Column('approved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_proposals', 'approved_at')
    # ### end Alembic commands ###
