"""add txt type

Revision ID: db7d5c9f3c13
Revises: 48aa56fa4093
Create Date: 2025-09-15 15:51:14.833718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7d5c9f3c13'
down_revision: Union[str, Sequence[str], None] = '48aa56fa4093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('tx_type', sa.Enum('Stake', 'Reward', 'Deposit', 'Withdrawal', 'Proposal', 'Vote', name='transaction_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'tx_type')
    # ### end Alembic commands ###
