"""Add payment status on vote

Revision ID: e923c6b1d893
Revises: db70a71f8846
Create Date: 2025-09-15 15:49:19.261076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e923c6b1d893'
down_revision: Union[str, Sequence[str], None] = 'db70a71f8846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal_votes', sa.Column('payment_status', sa.Enum('Pending', 'Complete', 'Failed', name='payment_status'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal_votes', 'payment_status')
    # ### end Alembic commands ###
